name: Build Cordova App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Cordova
      uses: amazingco/setup-cordova@v1
    - name: Build Android
      run: |
        cordova platform add android
        cordova build android
