name: Build Cordova App
on: [push]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js without cache
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        # HILANGKAN cache: 'npm' untuk menghindari error
    
    - name: Install Cordova
      run: npm install -g cordova
    
    - name: Build Cordova App
      run: |
        cordova create build-folder com.example.app MyApp
        cd build-folder
        cordova platform add android
        cordova build android --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build-folder/platforms/android/app/build/outputs/apk/release/
