name: Build Cordova APK
on: [push]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          myapp/package-lock.json
          package-lock.json
    
    - name: Install Cordova
      run: npm install -g cordova
    
    - name: Create Cordova project
      run: |
        cordova create myapp com.example.myapp MyApp
        cd myapp
        # Buat package.json untuk cache
        npm init -y
        cordova platform add android
    
    - name: Save cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          ~/.cordova
          myapp/platforms/android/.gradle
          myapp/node_modules
        key: ${{ runner.os }}-cordova-${{ hashFiles('myapp/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-cordova-
    
    - name: Build APK (not AAB)
      run: |
        cd myapp
        cordova build android --release -- --packageType=apk
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: myapp/platforms/android/app/build/outputs/apk/release/app-release.apk        # Force APK build instead of AAB
        cordova build android -- --packageType=apk
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-release-apk
        path: myapp/platforms/android/app/build/outputs/apk/release/*.apk
